name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vinicpires/vinicius-jackexperts:pipeline
      
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/vinicius-jackexperts:pipeline
      
    - name: Criar diretório .kube
      run: mkdir $HOME/.kube          
      
    - name: Desencriptar o arquivo de configuração p o diretório $HOME/.kube/config
      run: echo ${{secrets.KUBE_CONFIG}} | base64 --decode > $HOME/.kube/config
      
    - name: pegar kubeconfig
      run: cat $HOME/.kube/config
      
    - name: Testar conexão com o cluster
      run: kubectl cluster-info
      
    - name: Helm Lint
      run: helm lint charts/vinicius-pipeline
      
    - name: Helm Install
      run: helm install vinicius-pipeline ./charts/vinicius-pipeline --create-namespace -n vinicius-carvalho
