name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vinicpires/vinicius-jackexperts:pipeline
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/vinicius-jackexperts:pipeline
    - name: Test connection
      run: mkdir ${HOME}/.kube
           echo ${{secrets.KUBE_CONFIG}} | base64 --decode > ${HOME}/.kube/config
           cat ${HOME}/.kube/config
    - name: Test connection
      run: kubectl get nodes
    - name: Helm lint
      run: helm lint charts/vinicius-pipeline
    - name: Helm install
      run: helm install vinicius-pipeline ./charts/vinicius-pipeline --create-namespace -n vinicius-carvalho
